import Config

import_config "dotenv.exs"

config :tempmail, load_dotenv: true

# Configure your database. DATABASE_URL is supported so this Phoenix rewrite can
# share the same deployment style as the previous Next.js/Prisma app.
database_url = System.get_env("DATABASE_URL")

repo_config =
  if database_url do
    [url: database_url]
  else
    [
      username: "tempmail_phoenix",
      password: "tempmail_phoenix",
      hostname: "localhost",
      database: "tempmail_phoenix"
    ]
  end

config :tempmail, Tempmail.Repo,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  socket_options: [],
  parameters: [application_name: "tempmail_phoenix"],
  migration_timestamps: [type: :utc_datetime],
  migration_primary_key: [type: :binary_id],
  migration_foreign_key: [type: :binary_id],
  after_connect: {Postgrex, :query!, ["SET search_path TO public", []]}

config :tempmail, Tempmail.Repo, repo_config

config :tempmail,
  redis_url: System.get_env("REDIS_URL") || "redis://localhost:6379",
  default_domain: System.get_env("DEFAULT_DOMAIN") || "tempmail.com",
  default_email_ttl: String.to_integer(System.get_env("DEFAULT_EMAIL_TTL") || "600"),
  mail_server_hostname: System.get_env("MAIL_SERVER_HOSTNAME") || "mail.tempmailcentral.com",
  max_user_domains: String.to_integer(System.get_env("MAX_USER_DOMAINS") || "5"),
  mailcow_api_url: System.get_env("MAILCOW_API_URL") || "",
  mailcow_api_key: System.get_env("MAILCOW_API_KEY") || ""

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tempmail, TempmailWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "TRUzzwssmp2YBShmn03jn1TUJ5wE/uTMuyt9AouApJ66ni/vXMAuCaCepwwOnFjr",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tempmail, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tempmail, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :tempmail, TempmailWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/tempmail_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tempmail, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
